CREATE TABLE `PESOLONGITUD` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Semana` int(11) NOT NULL DEFAULT '-1',
  `Dias` int(11) NOT NULL DEFAULT '0',
  `Meses` int(11) NOT NULL DEFAULT '0',
  `Año` double NOT NULL DEFAULT '0',
  `Lpo` double NOT NULL DEFAULT '0' COMMENT 'curtosis peso niño',
  `Mpo` double NOT NULL DEFAULT '0' COMMENT 'media peso niño',
  `Spo` double NOT NULL DEFAULT '0' COMMENT 'coeficiente de variación peso niño',
  `S3npo` double NOT NULL DEFAULT '0',
  `S2npo` double NOT NULL DEFAULT '0',
  `S1npo` double NOT NULL DEFAULT '0',
  `S0po` double NOT NULL DEFAULT '0',
  `S1po` double NOT NULL DEFAULT '0',
  `S2po` double NOT NULL DEFAULT '0',
  `S3po` double NOT NULL DEFAULT '0',
  `Lto` double NOT NULL DEFAULT '0' COMMENT 'curtosis longitud niño',
  `Mto` double NOT NULL DEFAULT '0' COMMENT 'media longitud niño',
  `Sto` double NOT NULL DEFAULT '0' COMMENT 'coeficiente de variación longitud niño',
  `S3nto` double NOT NULL DEFAULT '0',
  `S2nto` double NOT NULL DEFAULT '0',
  `S1nto` double NOT NULL DEFAULT '0',
  `S0to` double NOT NULL DEFAULT '0',
  `S1to` double NOT NULL DEFAULT '0',
  `S2to` double NOT NULL DEFAULT '0',
  `S3to` double NOT NULL DEFAULT '0',
  `Lpa` double NOT NULL DEFAULT '0' COMMENT 'curtosis peso niña',
  `Mpa` double NOT NULL DEFAULT '0' COMMENT 'media peso niña',
  `Spa` double NOT NULL DEFAULT '0' COMMENT 'coeficiente de variación peso niña',
  `S3npa` double NOT NULL DEFAULT '0',
  `S2npa` double NOT NULL DEFAULT '0',
  `S1npa` double NOT NULL DEFAULT '0',
  `S0pa` double NOT NULL DEFAULT '0',
  `S1pa` double NOT NULL DEFAULT '0',
  `S2pa` double NOT NULL DEFAULT '0',
  `S3pa` double NOT NULL DEFAULT '0',
  `Lta` double NOT NULL DEFAULT '0' COMMENT 'curtosis longitud niña',
  `Mta` double NOT NULL DEFAULT '0' COMMENT 'media longitud niña',
  `Sta` double NOT NULL DEFAULT '0' COMMENT 'coeficiente de variación longitud niña',
  `S3nta` double NOT NULL DEFAULT '0',
  `S2nta` double NOT NULL DEFAULT '0',
  `S1nta` double NOT NULL DEFAULT '0',
  `S0ta` double NOT NULL DEFAULT '0',
  `S1ta` double NOT NULL DEFAULT '0',
  `S2ta` double NOT NULL DEFAULT '0',
  `S3ta` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=135 DEFAULT CHARSET=utf8 COMMENT='TABLA QUE ALMACENA LOS VALORES DE PESO Y LONGITUD PARA EL CALCULO Z';


CREATE TABLE `TABLAIMCPERICEFA` (
  `IdImc` int(11) NOT NULL AUTO_INCREMENT,
  `IdMes` int(11) NOT NULL COMMENT 'campo q representa la edad en meses del niño, ejemplo un niño o niña de 2 años 3 meses y 15 dias equibaldria a una edad de 26 meses, un niño o niña de 2 años 3 meses y 16 dias equibaldria a una edad de 27 meses',
  `Lio` double NOT NULL COMMENT 'L representa el exponente de simetria',
  `Mio` double NOT NULL COMMENT 'M representa la media',
  `Sio` double NOT NULL COMMENT 'S representa el coeficiente de variación',
  `SD4nio` double NOT NULL,
  `SD3nio` double NOT NULL,
  `SD2nio` double NOT NULL,
  `SD1nio` double NOT NULL,
  `SD0io` double NOT NULL,
  `SD1io` double NOT NULL,
  `SD2io` double NOT NULL,
  `SD3io` double NOT NULL,
  `SD4io` double NOT NULL,
  `Lia` double NOT NULL,
  `Mia` double NOT NULL,
  `Sia` double NOT NULL,
  `SD4nia` double NOT NULL,
  `SD3nia` double NOT NULL,
  `SD2nia` double NOT NULL,
  `SD1nia` double NOT NULL,
  `SD0ia` double NOT NULL,
  `SD1ia` double NOT NULL,
  `SD2ia` double NOT NULL,
  `SD3ia` double NOT NULL,
  `SD4ia` double NOT NULL,
  `Lpo` double NOT NULL COMMENT 'L del perímetro cefálico del niño',
  `Mpo` double NOT NULL COMMENT 'M del perímetro cefálico del niño',
  `Spo` double NOT NULL COMMENT 'S del perímtero cefálico de la niño',
  `Sdpo` double NOT NULL,
  `SD3npo` double NOT NULL,
  `SD2npo` double NOT NULL,
  `SD1npo` double NOT NULL,
  `SD0po` double NOT NULL,
  `SD1po` double NOT NULL,
  `SD2po` double NOT NULL,
  `SD3po` double NOT NULL,
  `Lpa` double NOT NULL COMMENT 'L del perímetro cefálico del niña\n',
  `Mpa` double NOT NULL COMMENT 'M del perímetro cefálico del niña',
  `Spa` double NOT NULL,
  `Sdpa` double NOT NULL,
  `SD3npa` double NOT NULL,
  `SD2npa` double NOT NULL,
  `SD1npa` double NOT NULL,
  `SD0pa` double NOT NULL,
  `SD1pa` double NOT NULL,
  `SD2pa` double NOT NULL,
  `SD3pa` double NOT NULL,
  PRIMARY KEY (`IdImc`,`IdMes`)
) ENGINE=InnoDB AUTO_INCREMENT=230 DEFAULT CHARSET=utf8 COMMENT='Tabla q almacena los datos del IMC y Perímetro Cefálico de Niños y Niñas. La terminacion en ''o'' representa a los niños. La terminacion en ''a'' representa a las niñas.\nTabla utilizada para el método LMS utilizado para construir, entre otras referencias, las curvas OMS y las curvas Argentinas.\nEste método permite q las variables con distribución asimétrica (ejemplo:peso) sean transformadas de forma tal q sean simétricas describiéndolas con tres parámetros, L (exponente de simetría), M (media) y S (coeficiente de variación) para cada Edad y Sexo. La fórmula para calcular el puntaje ''z'' por el mátodo LMS es la siguiente:\nZ = {[(Medición/M)^L]-1}/(L*S) ';
